### PR TITLE
Instructors page

### PR DESCRIPTION
**Pull request by pyninja-coder**
Instructors page added

### CODE REVIEW

**Review by GarretTomlin — CHANGES_REQUESTED** [review]
why you edited the footer?

**Comment by pyninja-coder** [comment]
> why you edited the footer?

The goal was to eventually create an instructor page for each instructor

**Comment by GarretTomlin** [comment]
> 

I see doubt you planning on finishing it?

**Comment by pyninja-coder** [comment]
> > 
> 
> I see doubt you planning on finishing it?

doubt it at this point 3 assignments due tomorrow

**Pull request merged**
